import 'package:ediku_s_application3/core/app_export.dart';import 'package:ediku_s_application3/presentation/available_shuttles_fortyfour_page/available_shuttles_fortyfour_page.dart';import 'package:ediku_s_application3/presentation/available_shuttles_thirtyfive_page/available_shuttles_thirtyfive_page.dart';import 'package:ediku_s_application3/widgets/app_bar/appbar_image.dart';import 'package:ediku_s_application3/widgets/app_bar/appbar_subtitle_2.dart';import 'package:ediku_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;class AvailableShuttlesThirtyfiveTabContainerScreen extends StatefulWidget {@override _AvailableShuttlesThirtyfiveTabContainerScreenState createState() =>  _AvailableShuttlesThirtyfiveTabContainerScreenState();
onTapArrowleft32(BuildContext context) { Navigator.pop(context); } 
 }

// ignore_for_file: must_be_immutable
class _AvailableShuttlesThirtyfiveTabContainerScreenState extends State<AvailableShuttlesThirtyfiveTabContainerScreen> with  TickerProviderStateMixin {TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 3, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, body: Container(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: double.maxFinite, child: Container(padding: getPadding(top: 3, bottom: 3), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup946), fit: BoxFit.cover)), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomAppBar(height: getVerticalSize(207), leadingWidth: 375, leading: AppbarImage(height: getSize(30), width: getSize(30), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 16, top: 29, right: 329, bottom: 38), onTap: () {onTapArrowleft32(context);}), centerTitle: true, title: Container(padding: getPadding(left: 120, top: 33, right: 120, bottom: 33), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup122), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [AppbarSubtitle2(text: "Tickets", margin: getMargin(left: 1, bottom: 7))])), styleType: Style.bgStyle_30)]))), Expanded(child: SingleChildScrollView(child: Container(decoration: AppDecoration.fillWhiteA700, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Container(height: getVerticalSize(22), width: getHorizontalSize(240), margin: getMargin(left: 15), child: TabBar(controller: tabviewController, labelColor: ColorConstant.gray800, labelStyle: TextStyle(fontSize: getFontSize(16), fontFamily: 'Lato', fontWeight: FontWeight.w500), unselectedLabelColor: ColorConstant.gray800, unselectedLabelStyle: TextStyle(fontSize: getFontSize(16), fontFamily: 'Lato', fontWeight: FontWeight.w500), indicatorColor: ColorConstant.green600, tabs: [Tab(child: Text("Booked", overflow: TextOverflow.ellipsis)), Tab(child: Text("Active", overflow: TextOverflow.ellipsis)), Tab(child: Text("Cancelled", overflow: TextOverflow.ellipsis))])), Container(height: getVerticalSize(704), child: TabBarView(controller: tabviewController, children: [AvailableShuttlesThirtyfivePage(), AvailableShuttlesFortyfourPage(), AvailableShuttlesFortyfourPage()]))]))))])))); } 
onTapArrowleft32(BuildContext context) { Navigator.pop(context); } 
 }
