import 'package:ediku_s_application3/core/app_export.dart';import 'package:ediku_s_application3/widgets/app_bar/appbar_image.dart';import 'package:ediku_s_application3/widgets/app_bar/appbar_subtitle_2.dart';import 'package:ediku_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:ediku_s_application3/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class TransactionHistoryOneScreen extends StatelessWidget {TextEditingController changepaymentpiController = TextEditingController();

TextEditingController resetpaymentpinController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, resizeToAvoidBottomInset: false, body: Container(height: size.height, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(svgPath: ImageConstant.imgGroup1045, height: getVerticalSize(823), width: getHorizontalSize(375), alignment: Alignment.center), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [Expanded(child: SingleChildScrollView(child: Container(height: size.height, width: double.maxFinite))), Padding(padding: getPadding(bottom: 577), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomAppBar(height: getVerticalSize(30), leadingWidth: 46, leading: AppbarImage(height: getSize(30), width: getSize(30), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 16), onTap: () {onTapArrowleft36(context);}), centerTitle: true, title: AppbarSubtitle2(text: "Payment PIN")), CustomTextFormField(focusNode: FocusNode(), autofocus: true, controller: changepaymentpiController, hintText: "Change Payment PIN", margin: getMargin(left: 16, top: 59, right: 17), variant: TextFormFieldVariant.OutlineBlack90023_1, padding: TextFormFieldPadding.PaddingAll13, fontStyle: TextFormFieldFontStyle.LatoMedium20), CustomTextFormField(focusNode: FocusNode(), autofocus: true, controller: resetpaymentpinController, hintText: "Reset Payment PIN", margin: getMargin(left: 16, top: 20, right: 17), variant: TextFormFieldVariant.OutlineBlack90023_1, padding: TextFormFieldPadding.PaddingAll13, fontStyle: TextFormFieldFontStyle.LatoMedium20, textInputAction: TextInputAction.done)]))]))])))); } 
onTapArrowleft36(BuildContext context) { Navigator.pop(context); } 
 }
