import 'package:ediku_s_application3/core/app_export.dart';import 'package:ediku_s_application3/widgets/app_bar/appbar_image.dart';import 'package:ediku_s_application3/widgets/app_bar/appbar_subtitle_2.dart';import 'package:ediku_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:ediku_s_application3/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;
// ignore_for_file: must_be_immutable
class AvailableShuttlesTwentyfourScreen extends StatelessWidget {TextEditingController accountinformatController = TextEditingController();

TextEditingController paymentpinController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: double.maxFinite, child: Container(padding: getPadding(top: 3, bottom: 3), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup946), fit: BoxFit.cover)), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomAppBar(height: getVerticalSize(206), leadingWidth: 375, leading: AppbarImage(height: getSize(30), width: getSize(30), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 16, top: 29, right: 329, bottom: 38), onTap: () {onTapArrowleft22(context);}), centerTitle: true, title: Container(padding: getPadding(left: 108, top: 35, right: 108, bottom: 35), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup122), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [AppbarSubtitle2(text: "Payments", margin: getMargin(left: 1, bottom: 3))])), styleType: Style.bgStyle_20)]))), Expanded(child: SingleChildScrollView(child: Container(padding: getPadding(left: 15, top: 32, right: 15, bottom: 32), decoration: AppDecoration.fillWhiteA700, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomTextFormField(focusNode: FocusNode(), autofocus: true, controller: accountinformatController, hintText: "Account information", variant: TextFormFieldVariant.OutlineBlack90023_1, padding: TextFormFieldPadding.PaddingT18, fontStyle: TextFormFieldFontStyle.LatoMedium16Green600), CustomTextFormField(focusNode: FocusNode(), autofocus: true, controller: paymentpinController, hintText: "Payment PIN", margin: getMargin(top: 24, bottom: 545), variant: TextFormFieldVariant.OutlineBlack90023_1, padding: TextFormFieldPadding.PaddingT18, fontStyle: TextFormFieldFontStyle.LatoMedium16Green600, textInputAction: TextInputAction.done)]))))])))); } 
onTapArrowleft22(BuildContext context) { Navigator.pop(context); } 
 }
