import 'package:ediku_s_application3/core/app_export.dart';import 'package:ediku_s_application3/widgets/app_bar/appbar_image.dart';import 'package:ediku_s_application3/widgets/app_bar/appbar_subtitle_2.dart';import 'package:ediku_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:ediku_s_application3/widgets/custom_button.dart';import 'package:ediku_s_application3/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;
// ignore_for_file: must_be_immutable
class BookingStatusTwoScreen extends StatelessWidget {TextEditingController enterbookingnumController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: Container(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: double.maxFinite, child: Container(padding: getPadding(top: 3, bottom: 3), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup946), fit: BoxFit.cover)), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomAppBar(height: getVerticalSize(206), leadingWidth: 375, leading: AppbarImage(height: getSize(30), width: getSize(30), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 16, top: 29, right: 329, bottom: 38), onTap: () {onTapArrowleft18(context);}), centerTitle: true, title: Container(padding: getPadding(left: 81, top: 35, right: 81, bottom: 35), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup122), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [AppbarSubtitle2(text: "Booking history", margin: getMargin(left: 1, bottom: 3))])), styleType: Style.bgStyle_16)]))), Expanded(child: SingleChildScrollView(child: Container(padding: getPadding(left: 16, top: 52, right: 16, bottom: 52), decoration: AppDecoration.fillWhiteA700, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [CustomTextFormField(focusNode: FocusNode(), autofocus: true, controller: enterbookingnumController, hintText: "Enter Booking number", variant: TextFormFieldVariant.None, fontStyle: TextFormFieldFontStyle.LatoMedium14Gray60001, textInputAction: TextInputAction.done, textInputType: TextInputType.number), CustomButton(height: getVerticalSize(51), text: "Check status", margin: getMargin(top: 49, bottom: 468), variant: ButtonVariant.OutlineBlack90023_3)]))))]))))); } 
onTapArrowleft18(BuildContext context) { Navigator.pop(context); } 
 }
